#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ] || [ "$1" = "purge" ]; then
  systemctl stop pbi.service >/dev/null 2>&1 || true
  systemctl disable pbi.service >/dev/null 2>&1 || true
fi

exit 0
